before_script:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh
  - chmod +x cmake-3.10.2-Linux-x86_64.sh
  - ./cmake-3.10.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_7:
  image: gcc:7
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DMART_COMMON_INCLUDE_TESTS=ON
    - make all
    - ctest .

build_latest:
  image: gcc:latest
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DMART_COMMON_INCLUDE_TESTS=ON
    - make all
    - make testing_mart-common
    - ctest .

