language: cpp

os: linux

sudo: false

git:
  depth: 5

notifications:
  email:
    on_success: never
    on_failure: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - lcov

script:
  - export CXX=g++-8
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DMART_COMMON_INCLUDE_TESTS=ON -DMART_COMMON_UPLOAD_COVERAGE=On
  - cmake --build .
  - ctest .
  - make testing_mart-common_coverage
  - bash <(curl -s https://codecov.io/bash)

