language: cpp

os: linux

dist: bionic

git:
  depth: 5

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - g++-8

env:
  global:
    - BUILD_DIR_MAIN=${TRAVIS_BUILD_DIR}/build
    - BUILD_DIR_EXAMPLE=${TRAVIS_BUILD_DIR}/build_example
    - INSTALL_DIR=${TRAVIS_BUILD_DIR}/install
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_VERSION=3.16.3-Linux-x86_64
    - CMAKE_URL=https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-${CMAKE_VERSION}.tar.gz
  jobs:
    - CC=gcc-8 CXX=g++-8
    - CC=clang CXX=clang++

jobs:
  include:
    - name: CheckCxx11Compat
      script:
        - cmake -DCMAKE_CXX_STANDARD=11 .
        - cmake --build . --target mart-netlib-portlayer
    - name: CheckInstallation
      env: CC=gcc-8 CXX=g++-8
      script:
        - cmake -S ${TRAVIS_BUILD_DIR} -B ${BUILD_DIR_MAIN} -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} -DCMAKE_INSTALL_MESSAGE=NEVER -DCMAKE_BUILD_TYPE=Debug
        - cmake --build ${BUILD_DIR_MAIN} --target install
        - cmake -S ${TRAVIS_BUILD_DIR}/examples/nw -B ${BUILD_DIR_EXAMPLE} -DCMAKE_PREFIX_PATH=${INSTALL_DIR} -DCMAKE_BUILD_TYPE=Debug -DMART_COMMON_EXAMPLE_NW_USE_INSTALLED_LIBRARIES=ON
        - cmake --build ${BUILD_DIR_EXAMPLE}
        - ${BUILD_DIR_EXAMPLE}/mart-common_ex_udp_sender
        - ${BUILD_DIR_EXAMPLE}/mart-common_ex_udp_server


# the install step will take care of deploying a newer cmake version
install:
  - mkdir -p ${DEPS_DIR}
  - travis_retry wget ${CMAKE_URL} -P ${DEPS_DIR}
  - tar -xvf ${DEPS_DIR}/cmake-${CMAKE_VERSION}.tar.gz -C ${DEPS_DIR}
  - mv ${DEPS_DIR}/cmake-${CMAKE_VERSION} ${DEPS_DIR}/cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH

script:
  - cmake --version
  - cmake -S ${TRAVIS_BUILD_DIR} -B ${BUILD_DIR_MAIN} -DCMAKE_BUILD_TYPE=Debug -DMART_COMMON_INCLUDE_TESTS=ON -DMART_COMMON_INCLUDE_EXAMPLES=ON -DMART_NETLIB_TEST_UNIX_DOMAIN_SOCKS=ON
  - cmake --build ${BUILD_DIR_MAIN}
  - cd ${BUILD_DIR_MAIN} && ctest --output-on-failure && cd -

