language: cpp

os: linux

sudo: false

git:
  depth: 1

notifications:
  email:
    on_success: never
    on_failure: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - lcov

script:
  - export CXX=g++-7
  - mkdir -p build && cd build
  - cmake .. -DMART_COMMON_INCLUDE_TESTS=ON
  - make all
  - ctest .