language: cpp

os: linux
dist: bionic

jobs:
  include:
    - name: gcc-default
      before_install:
        - export CC=gcc && export CXX=g++
        - export CXX_STD=17

    - name: clang-default
      before_install:
        - export CC=clang && export CXX=clang++
        - export CXX_STD=17

    - name: gcc-10
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt update
        - sudo apt install g++-10
        - export CC=gcc-10 && export CXX=g++-10
        - export CXX_STD=20

    - name: clang-10
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt update
        - sudo apt install g++-10
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo add-apt-repository -y "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
        - sudo apt update
        - sudo apt install clang-10
        - export CC=clang-10 && export CXX=clang++-10
        - export CXX_STD=20


install:
  - git clone https://github.com/catchorg/Catch2.git && mkdir -p Catch2/build && cd Catch2/build
  - cmake -DCMAKE_INSTALL_PREFIX=~/cmake_local -DCATCH_BUILD_TESTING=OFF -DCATCH_ENABLE_WERROR=OFF -DCATCH_INSTALL_DOCS=OFF ..
  - cmake --build . --target install
  - cd ../..

script:
  - mkdir build && cd build
  - cmake -DCMAKE_PREFIX_PATH=~/cmake_local -DCMAKE_BUILD_TYPE=Debug -DIM_STR_INCLUDE_TESTS=ON -DIM_STR_RUN_SANITIZERS=ON -DCMAKE_CXX_EXTENSIONS=Off -DCMAKE_CXX_STANDARD=${CXX_STD} ..
  - cmake --build . -- -j2
  - ctest .
